import React from 'react';

export const BannerAd = () => null;

export const BannerAdSize = {
  BANNER: 'BANNER',
  FULL_BANNER: 'FULL_BANNER',
  LARGE_BANNER: 'LARGE_BANNER',
  LEADERBOARD: 'LEADERBOARD',
  MEDIUM_RECTANGLE: 'MEDIUM_RECTANGLE',
  PORTRAIT: 'PORTRAIT',
  SMART_BANNER: 'SMART_BANNER',
  WIDE_SKYSCRAPER: 'WIDE_SKYSCRAPER',
  ANCHORED_ADAPTIVE_BANNER: 'ANCHORED_ADAPTIVE_BANNER',
  INLINE_ADAPTIVE_BANNER: 'INLINE_ADAPTIVE_BANNER',
};
