CREATE TABLE IF NOT EXISTS public.ratoire_pistes (
    id bigint generated by default as identity primary key,
    nom_sujet text not null,
    type_sujet text not null,
    annee_origine integer,
    created_at timestamptz default now()
);

-- Autoriser l'accès
GRANT ALL ON TABLE public.ratoire_pistes TO anon, authenticated, service_role;